// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FirebaseAPI'),
    appId: '1:68975839347:web:cd11cc4db1daf7604c8206',
    messagingSenderId: '68975839347',
    projectId: 'sust-ai-n',
    authDomain: 'sust-ai-n.firebaseapp.com',
    storageBucket: 'sust-ai-n.firebasestorage.app',
    measurementId: 'G-0H52LBRB5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FirebaseAPI2'),
    appId: '1:68975839347:android:2cccb5b20aac2e814c8206',
    messagingSenderId: '68975839347',
    projectId: 'sust-ai-n',
    storageBucket: 'sust-ai-n.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FirebaseAPI3'),
    appId: '1:68975839347:ios:36c18703957810ed4c8206',
    messagingSenderId: '68975839347',
    projectId: 'sust-ai-n',
    storageBucket: 'sust-ai-n.firebasestorage.app',
    iosBundleId: 'com.example.sustAin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FirebaseAPI4'),
    appId: '1:68975839347:ios:36c18703957810ed4c8206',
    messagingSenderId: '68975839347',
    projectId: 'sust-ai-n',
    storageBucket: 'sust-ai-n.firebasestorage.app',
    iosBundleId: 'com.example.sustAin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FirebaseAPI5'),
    appId: '1:68975839347:web:05b44503dde62bfd4c8206',
    messagingSenderId: '68975839347',
    projectId: 'sust-ai-n',
    authDomain: 'sust-ai-n.firebaseapp.com',
    storageBucket: 'sust-ai-n.firebasestorage.app',
    measurementId: 'G-MT8FG7L7K8',
  );
}
